### ISSUE TITLE
not an issue: a question

### ISSUE THREAD

**Issue by arasharchor** [tchaton/Image-Annotation-Website-for-Deep-Learning-Project#1]
Hi, 

I tried your tool. thanks for sharing it. I like to do crowdsourcing for object detection problem. I'd like to this feature and put this tool on the net. Could you give me a hint from where I can start?

Best,

**Comment by tchaton** [comment]
Hi,

This is a very stupid tool :) It made it to annotate images/ remove bad ones from dataset. People connect to it. It load random images from /imgs folder and load it inside the html page.
U have both an input (for annotation) and a 0/1 value to keep or remove the images from the dataset and a before/next button. It sends it to a python server that will save it to a json format.
I think it keeps {annotation,path_images,keep_or_not} and the reduce allows to aggregate several jsons file and give a json with {path_image,[anno0,ann1,...],keep_or_not}.

It is not really to do what u want, And I did it in one afternoon to help me but never use it.

Best regards, Thomas Chaton.

-----------------------
Thomas CHATON
Graduated in Numeric Security / Data science in 2017
TELECOM ParisTech/Eurecom
France
Tel : +33 (0) 6 46 57 50 65

**Comment by tchaton** [comment]
Hi man,

It was my idea at first. Look at imageNet or Visual Genome. You can create a little website with js that allow people to draw rectangles around objects and annotate it. You can make it faster by putting
pictures in folder and give recommendation to word to help people do it faster. The idea is to optimize the time to do it.

Best regards, T.C

-----------------------
Thomas CHATON
Graduated in Numeric Security / Data science in 2017
TELECOM ParisTech/Eurecom
France
Tel : +33 (0) 6 46 57 50 65

**Comment by arasharchor** [comment]
@tchaton I am working on it. The problem is that I am not familiar with web developing and javascript.  The only thing that I want is object detection. I know cpp and python, but not much js which I have to learn. Do you have an sample in js which one can put rectangle around object and ground truth would be in Pascal VOC format?

**Comment by tchaton** [comment]
Hi,

No I dont . But you cant find anything about code on either forum or github. And it is great to know js, believe me ;) Good luck.

Best Regards, Thomas Chaton.


-----------------------
Thomas CHATON
Graduated in Numeric Security / Data science in 2017
TELECOM ParisTech/Eurecom
France
Tel : +33 (0) 6 46 57 50 65
hub.com/tchaton/Image-Annotation-Website-for-Deep-Learning-Project/issues/1#issuecomment-308288962
